export default {
  ParsedResults: [
    {
      TextOverlay: {
        Lines: [
          {
            LineText: 'Invoice INVOOIO',
            Words: [
              {
                WordText: 'Invoice',
                Left: 273,
                Top: 253,
                Height: 32,
                Width: 140,
              },
              {
                WordText: 'INVOOIO',
                Left: 427,
                Top: 253,
                Height: 32,
                Width: 157,
              },
            ],
            MaxHeight: 32,
            MinTop: 253,
          },
          {
            LineText: 'To',
            Words: [
              {
                WordText: 'To',
                Left: 272,
                Top: 306,
                Height: 23,
                Width: 35,
              },
            ],
            MaxHeight: 23,
            MinTop: 306,
          },
          {
            LineText: 'Jackie Kensington',
            Words: [
              {
                WordText: 'Jackie',
                Left: 272,
                Top: 340,
                Height: 23,
                Width: 83,
              },
              {
                WordText: 'Kensington',
                Left: 365,
                Top: 340,
                Height: 29,
                Width: 146,
              },
            ],
            MaxHeight: 29,
            MinTop: 340,
          },
          {
            LineText: '18 High St',
            Words: [
              {
                WordText: '18',
                Left: 274,
                Top: 374,
                Height: 22,
                Width: 30,
              },
              {
                WordText: 'High',
                Left: 315,
                Top: 373,
                Height: 29,
                Width: 57,
              },
              {
                WordText: 'St',
                Left: 383,
                Top: 373,
                Height: 23,
                Width: 27,
              },
            ],
            MaxHeight: 29,
            MinTop: 373,
          },
          {
            LineText: 'Wickham',
            Words: [
              {
                WordText: 'Wickham',
                Left: 272,
                Top: 407,
                Height: 23,
                Width: 120,
              },
            ],
            MaxHeight: 23,
            MinTop: 407,
          },
          {
            LineText: 'WK12 6HK',
            Words: [
              {
                WordText: 'WK12',
                Left: 272,
                Top: 440,
                Height: 23,
                Width: 79,
              },
              {
                WordText: '6HK',
                Left: 361,
                Top: 440,
                Height: 23,
                Width: 57,
              },
            ],
            MaxHeight: 23,
            MinTop: 440,
          },
          {
            LineText: 'Certificate Number CER/123-34',
            Words: [
              {
                WordText: 'Certificate',
                Left: 429,
                Top: 600,
                Height: 23,
                Width: 131,
              },
              {
                WordText: 'Number',
                Left: 571,
                Top: 601,
                Height: 22,
                Width: 103,
              },
              {
                WordText: 'CER/123-34',
                Left: 692,
                Top: 600,
                Height: 23,
                Width: 161,
              },
            ],
            MaxHeight: 23,
            MinTop: 600,
          },
          {
            LineText: 'Engineer David',
            Words: [
              {
                WordText: 'Engineer',
                Left: 558,
                Top: 651,
                Height: 29,
                Width: 116,
              },
              {
                WordText: 'David',
                Left: 693,
                Top: 651,
                Height: 23,
                Width: 72,
              },
            ],
            MaxHeight: 29,
            MinTop: 651,
          },
          {
            LineText: 'Item',
            Words: [
              {
                WordText: 'Item',
                Left: 274,
                Top: 1084,
                Height: 23,
                Width: 54,
              },
            ],
            MaxHeight: 23,
            MinTop: 1084,
          },
          {
            LineText: 'Electrical Labour',
            Words: [
              {
                WordText: 'Electrical',
                Left: 274,
                Top: 1190,
                Height: 23,
                Width: 128,
              },
              {
                WordText: 'Labour',
                Left: 413,
                Top: 1191,
                Height: 22,
                Width: 99,
              },
            ],
            MaxHeight: 23,
            MinTop: 1190,
          },
          {
            LineText: 'Electrical',
            Words: [
              {
                WordText: 'Electrical',
                Left: 1469,
                Top: 455,
                Height: 55,
                Width: 243,
              },
            ],
            MaxHeight: 55,
            MinTop: 455,
          },
          {
            LineText: 'Sevices Lü•nited',
            Words: [
              {
                WordText: 'Sevices',
                Left: 1488,
                Top: 522,
                Height: 22,
                Width: 89,
              },
              {
                WordText: 'Lü•nited',
                Left: 1584,
                Top: 522,
                Height: 22,
                Width: 89,
              },
            ],
            MaxHeight: 22,
            MinTop: 522,
          },
          {
            LineText: 'From',
            Words: [
              {
                WordText: 'From',
                Left: 1642,
                Top: 600,
                Height: 22,
                Width: 71,
              },
            ],
            MaxHeight: 22,
            MinTop: 600,
          },
          {
            LineText: 'MJ Electrical Services',
            Words: [
              {
                WordText: 'MJ',
                Left: 1426,
                Top: 637,
                Height: 23,
                Width: 37,
              },
              {
                WordText: 'Electrical',
                Left: 1474,
                Top: 637,
                Height: 23,
                Width: 117,
              },
              {
                WordText: 'Services',
                Left: 1601,
                Top: 636,
                Height: 24,
                Width: 112,
              },
            ],
            MaxHeight: 24,
            MinTop: 636,
          },
          {
            LineText: '17 Harold Grove, Woodhouse, Leeds,',
            Words: [
              {
                WordText: '17',
                Left: 1220,
                Top: 674,
                Height: 22,
                Width: 29,
              },
              {
                WordText: 'Harold',
                Left: 1260,
                Top: 674,
                Height: 23,
                Width: 84,
              },
              {
                WordText: 'Grove,',
                Left: 1355,
                Top: 673,
                Height: 27,
                Width: 85,
              },
              {
                WordText: 'Woodhouse,',
                Left: 1451,
                Top: 674,
                Height: 27,
                Width: 164,
              },
              {
                WordText: 'Leeds,',
                Left: 1627,
                Top: 674,
                Height: 27,
                Width: 85,
              },
            ],
            MaxHeight: 27,
            MinTop: 673,
          },
          {
            LineText: 'West Yorkshire, LS6 2EZ',
            Words: [
              {
                WordText: 'West',
                Left: 1382,
                Top: 711,
                Height: 22,
                Width: 67,
              },
              {
                WordText: 'Yorkshire,',
                Left: 1458,
                Top: 711,
                Height: 26,
                Width: 130,
              },
              {
                WordText: 'LS6',
                Left: 1600,
                Top: 710,
                Height: 23,
                Width: 51,
              },
              {
                WordText: '2EZ',
                Left: 1660,
                Top: 711,
                Height: 22,
                Width: 54,
              },
            ],
            MaxHeight: 26,
            MinTop: 710,
          },
          {
            LineText: 'Email: info@ mj-electrcial.co.uk',
            Words: [
              {
                WordText: 'Email:',
                Left: 1296,
                Top: 748,
                Height: 23,
                Width: 79,
              },
              {
                WordText: 'info@',
                Left: 1386,
                Top: 747,
                Height: 24,
                Width: 74,
              },
              {
                WordText: 'mj-electrcial.co.uk',
                Left: 1479,
                Top: 748,
                Height: 28,
                Width: 235,
              },
            ],
            MaxHeight: 28,
            MinTop: 747,
          },
          {
            LineText: 'Due Date',
            Words: [
              {
                WordText: 'Due',
                Left: 1249,
                Top: 891,
                Height: 31,
                Width: 71,
              },
              {
                WordText: 'Date',
                Left: 1336,
                Top: 891,
                Height: 31,
                Width: 84,
              },
            ],
            MaxHeight: 31,
            MinTop: 891,
          },
          {
            LineText: 'Invoice Date',
            Words: [
              {
                WordText: 'Invoice',
                Left: 1194,
                Top: 958,
                Height: 31,
                Width: 126,
              },
              {
                WordText: 'Date',
                Left: 1336,
                Top: 958,
                Height: 31,
                Width: 83,
              },
            ],
            MaxHeight: 31,
            MinTop: 958,
          },
          {
            LineText: 'Tel: 441132816781',
            Words: [
              {
                WordText: 'Tel:',
                Left: 1459,
                Top: 784,
                Height: 24,
                Width: 48,
              },
              {
                WordText: '441132816781',
                Left: 1517,
                Top: 785,
                Height: 23,
                Width: 191,
              },
            ],
            MaxHeight: 24,
            MinTop: 784,
          },
          {
            LineText: '17th Mar 2012',
            Words: [
              {
                WordText: '17th',
                Left: 1459,
                Top: 891,
                Height: 31,
                Width: 75,
              },
              {
                WordText: 'Mar',
                Left: 1550,
                Top: 891,
                Height: 31,
                Width: 69,
              },
              {
                WordText: '2012',
                Left: 1631,
                Top: 891,
                Height: 31,
                Width: 90,
              },
            ],
            MaxHeight: 31,
            MinTop: 891,
          },
          {
            LineText: '16th Feb 2012',
            Words: [
              {
                WordText: '16th',
                Left: 1459,
                Top: 958,
                Height: 31,
                Width: 74,
              },
              {
                WordText: 'Feb',
                Left: 1550,
                Top: 958,
                Height: 31,
                Width: 68,
              },
              {
                WordText: '2012',
                Left: 1631,
                Top: 959,
                Height: 30,
                Width: 90,
              },
            ],
            MaxHeight: 31,
            MinTop: 958,
          },
          {
            LineText: 'Quantity Unit Price Line Price',
            Words: [
              {
                WordText: 'Quantity',
                Left: 1291,
                Top: 1084,
                Height: 29,
                Width: 109,
              },
              {
                WordText: 'Unit',
                Left: 1434,
                Top: 1084,
                Height: 23,
                Width: 50,
              },
              {
                WordText: 'Price',
                Left: 1494,
                Top: 1084,
                Height: 23,
                Width: 65,
              },
              {
                WordText: 'Line',
                Left: 1583,
                Top: 1084,
                Height: 23,
                Width: 53,
              },
              {
                WordText: 'Price',
                Left: 1647,
                Top: 1084,
                Height: 23,
                Width: 65,
              },
            ],
            MaxHeight: 29,
            MinTop: 1084,
          },
          {
            LineText: 'Installation carried out on flat 18. Installed 3 new',
            Words: [
              {
                WordText: 'Installation',
                Left: 353,
                Top: 1230,
                Height: 24,
                Width: 172,
              },
              {
                WordText: 'carried',
                Left: 548,
                Top: 1230,
                Height: 24,
                Width: 107,
              },
              {
                WordText: 'out',
                Left: 677,
                Top: 1233,
                Height: 21,
                Width: 48,
              },
              {
                WordText: 'on',
                Left: 747,
                Top: 1237,
                Height: 17,
                Width: 34,
              },
              {
                WordText: 'flat',
                Left: 802,
                Top: 1230,
                Height: 24,
                Width: 51,
              },
              {
                WordText: '18.',
                Left: 876,
                Top: 1230,
                Height: 24,
                Width: 42,
              },
              {
                WordText: 'Installed',
                Left: 940,
                Top: 1230,
                Height: 24,
                Width: 130,
              },
              {
                WordText: '3',
                Left: 1093,
                Top: 1230,
                Height: 24,
                Width: 14,
              },
              {
                WordText: 'new',
                Left: 1130,
                Top: 1237,
                Height: 17,
                Width: 56,
              },
            ],
            MaxHeight: 24,
            MinTop: 1230,
          },
          {
            LineText: 'brass effect plug fittings. Checked fuses.',
            Words: [
              {
                WordText: 'brass',
                Left: 353,
                Top: 1265,
                Height: 23,
                Width: 80,
              },
              {
                WordText: 'effect',
                Left: 455,
                Top: 1265,
                Height: 23,
                Width: 87,
              },
              {
                WordText: 'plug',
                Left: 564,
                Top: 1265,
                Height: 30,
                Width: 63,
              },
              {
                WordText: 'fittings.',
                Left: 647,
                Top: 1265,
                Height: 30,
                Width: 116,
              },
              {
                WordText: 'Checked',
                Left: 785,
                Top: 1264,
                Height: 24,
                Width: 128,
              },
              {
                WordText: 'fuses.',
                Left: 935,
                Top: 1265,
                Height: 23,
                Width: 88,
              },
            ],
            MaxHeight: 30,
            MinTop: 1264,
          },
          {
            LineText: 'Reconnected light switch and fitted dimmer in living',
            Words: [
              {
                WordText: 'Reconnected',
                Left: 353,
                Top: 1299,
                Height: 24,
                Width: 197,
              },
              {
                WordText: 'light',
                Left: 573,
                Top: 1299,
                Height: 30,
                Width: 65,
              },
              {
                WordText: 'switch',
                Left: 659,
                Top: 1299,
                Height: 24,
                Width: 94,
              },
              {
                WordText: 'and',
                Left: 775,
                Top: 1299,
                Height: 24,
                Width: 53,
              },
              {
                WordText: 'fitted',
                Left: 850,
                Top: 1299,
                Height: 24,
                Width: 81,
              },
              {
                WordText: 'dimmer',
                Left: 954,
                Top: 1299,
                Height: 24,
                Width: 112,
              },
              {
                WordText: 'in',
                Left: 1088,
                Top: 1300,
                Height: 23,
                Width: 22,
              },
              {
                WordText: 'living',
                Left: 1134,
                Top: 1299,
                Height: 30,
                Width: 79,
              },
            ],
            MaxHeight: 30,
            MinTop: 1299,
          },
          {
            LineText: 'room. 4 hours on site at f 33 per hour.',
            Words: [
              {
                WordText: 'room.',
                Left: 353,
                Top: 1340,
                Height: 17,
                Width: 84,
              },
              {
                WordText: '4',
                Left: 459,
                Top: 1333,
                Height: 24,
                Width: 15,
              },
              {
                WordText: 'hours',
                Left: 496,
                Top: 1333,
                Height: 24,
                Width: 84,
              },
              {
                WordText: 'on',
                Left: 602,
                Top: 1340,
                Height: 17,
                Width: 34,
              },
              {
                WordText: 'site',
                Left: 658,
                Top: 1334,
                Height: 23,
                Width: 53,
              },
              {
                WordText: 'at',
                Left: 733,
                Top: 1337,
                Height: 20,
                Width: 29,
              },
              {
                WordText: 'f',
                Left: 784,
                Top: 1333,
                Height: 24,
                Width: 13,
              },
              {
                WordText: '33',
                Left: 802,
                Top: 1333,
                Height: 24,
                Width: 34,
              },
              {
                WordText: 'per',
                Left: 859,
                Top: 1340,
                Height: 23,
                Width: 47,
              },
              {
                WordText: 'hour.',
                Left: 927,
                Top: 1333,
                Height: 24,
                Width: 76,
              },
            ],
            MaxHeight: 24,
            MinTop: 1333,
          },
          {
            LineText:
              'Volex 13A 2G DP sw Skt Wht Ins BB Round Edge Brass Effect',
            Words: [
              {
                WordText: 'Volex',
                Left: 272,
                Top: 1412,
                Height: 23,
                Width: 79,
              },
              {
                WordText: '13A',
                Left: 360,
                Top: 1413,
                Height: 22,
                Width: 53,
              },
              {
                WordText: '2G',
                Left: 422,
                Top: 1412,
                Height: 23,
                Width: 37,
              },
              {
                WordText: 'DP',
                Left: 471,
                Top: 1413,
                Height: 22,
                Width: 38,
              },
              {
                WordText: 'sw',
                Left: 520,
                Top: 1412,
                Height: 23,
                Width: 41,
              },
              {
                WordText: 'Skt',
                Left: 570,
                Top: 1412,
                Height: 23,
                Width: 45,
              },
              {
                WordText: 'Wht',
                Left: 624,
                Top: 1412,
                Height: 23,
                Width: 55,
              },
              {
                WordText: 'Ins',
                Left: 689,
                Top: 1412,
                Height: 23,
                Width: 41,
              },
              {
                WordText: 'BB',
                Left: 740,
                Top: 1413,
                Height: 22,
                Width: 40,
              },
              {
                WordText: 'Round',
                Left: 791,
                Top: 1412,
                Height: 23,
                Width: 91,
              },
              {
                WordText: 'Edge',
                Left: 893,
                Top: 1412,
                Height: 29,
                Width: 71,
              },
              {
                WordText: 'Brass',
                Left: 974,
                Top: 1413,
                Height: 22,
                Width: 79,
              },
              {
                WordText: 'Effect',
                Left: 1064,
                Top: 1412,
                Height: 23,
                Width: 80,
              },
            ],
            MaxHeight: 29,
            MinTop: 1412,
          },
          {
            LineText: 'Volex 4G IW 250W Dimmer Brushed Brass Round Edge',
            Words: [
              {
                WordText: 'Volex',
                Left: 272,
                Top: 1501,
                Height: 23,
                Width: 78,
              },
              {
                WordText: '4G',
                Left: 359,
                Top: 1501,
                Height: 23,
                Width: 38,
              },
              {
                WordText: 'IW',
                Left: 408,
                Top: 1501,
                Height: 22,
                Width: 43,
              },
              {
                WordText: '250W',
                Left: 460,
                Top: 1501,
                Height: 23,
                Width: 76,
              },
              {
                WordText: 'Dimmer',
                Left: 547,
                Top: 1501,
                Height: 23,
                Width: 108,
              },
              {
                WordText: 'Brushed',
                Left: 665,
                Top: 1501,
                Height: 23,
                Width: 117,
              },
              {
                WordText: 'Brass',
                Left: 793,
                Top: 1501,
                Height: 23,
                Width: 80,
              },
              {
                WordText: 'Round',
                Left: 884,
                Top: 1501,
                Height: 23,
                Width: 90,
              },
              {
                WordText: 'Edge',
                Left: 985,
                Top: 1501,
                Height: 28,
                Width: 71,
              },
            ],
            MaxHeight: 28,
            MinTop: 1501,
          },
          {
            LineText: '4',
            Words: [
              {
                WordText: '4',
                Left: 1396,
                Top: 1191,
                Height: 22,
                Width: 16,
              },
            ],
            MaxHeight: 22,
            MinTop: 1191,
          },
          {
            LineText: '3',
            Words: [
              {
                WordText: '3',
                Left: 1396,
                Top: 1413,
                Height: 22,
                Width: 15,
              },
            ],
            MaxHeight: 22,
            MinTop: 1413,
          },
          {
            LineText: '1',
            Words: [
              {
                WordText: '1',
                Left: 1398,
                Top: 1502,
                Height: 21,
                Width: 9,
              },
            ],
            MaxHeight: 21,
            MinTop: 1502,
          },
          {
            LineText: 'Subtotal',
            Words: [
              {
                WordText: 'Subtotal',
                Left: 1287,
                Top: 1831,
                Height: 28,
                Width: 127,
              },
            ],
            MaxHeight: 28,
            MinTop: 1831,
          },
          {
            LineText: 'VAT',
            Words: [
              {
                WordText: 'VAT',
                Left: 1347,
                Top: 1882,
                Height: 27,
                Width: 68,
              },
            ],
            MaxHeight: 27,
            MinTop: 1882,
          },
          {
            LineText: 'Total',
            Words: [
              {
                WordText: 'Total',
                Left: 1336,
                Top: 1932,
                Height: 28,
                Width: 78,
              },
            ],
            MaxHeight: 28,
            MinTop: 1932,
          },
          {
            LineText: '233.00',
            Words: [
              {
                WordText: '233.00',
                Left: 1473,
                Top: 1191,
                Height: 22,
                Width: 89,
              },
            ],
            MaxHeight: 22,
            MinTop: 1191,
          },
          {
            LineText: '215.57',
            Words: [
              {
                WordText: '215.57',
                Left: 1473,
                Top: 1413,
                Height: 22,
                Width: 90,
              },
            ],
            MaxHeight: 22,
            MinTop: 1413,
          },
          {
            LineText: '232.00',
            Words: [
              {
                WordText: '232.00',
                Left: 1473,
                Top: 1501,
                Height: 23,
                Width: 89,
              },
            ],
            MaxHeight: 23,
            MinTop: 1501,
          },
          {
            LineText: '2132.00',
            Words: [
              {
                WordText: '2132.00',
                Left: 1608,
                Top: 1191,
                Height: 22,
                Width: 105,
              },
            ],
            MaxHeight: 22,
            MinTop: 1191,
          },
          {
            LineText: '246.71',
            Words: [
              {
                WordText: '246.71',
                Left: 1624,
                Top: 1412,
                Height: 23,
                Width: 84,
              },
            ],
            MaxHeight: 23,
            MinTop: 1412,
          },
          {
            LineText: 'E32.OO',
            Words: [
              {
                WordText: 'E32.OO',
                Left: 1624,
                Top: 1501,
                Height: 23,
                Width: 89,
              },
            ],
            MaxHeight: 23,
            MinTop: 1501,
          },
          {
            LineText: '2210.71',
            Words: [
              {
                WordText: '2210.71',
                Left: 1590,
                Top: 1835,
                Height: 27,
                Width: 121,
              },
            ],
            MaxHeight: 27,
            MinTop: 1835,
          },
          {
            LineText: '242.14',
            Words: [
              {
                WordText: '242.14',
                Left: 1609,
                Top: 1885,
                Height: 27,
                Width: 108,
              },
            ],
            MaxHeight: 27,
            MinTop: 1885,
          },
          {
            LineText: '2252.85',
            Words: [
              {
                WordText: '2252.85',
                Left: 1590,
                Top: 1936,
                Height: 27,
                Width: 126,
              },
            ],
            MaxHeight: 27,
            MinTop: 1936,
          },
          {
            LineText:
              "Thank you for your business Please make all cheques payable to 'Company Name'. For bank transfers 'HSBC', sort code",
            Words: [
              {
                WordText: 'Thank',
                Left: 290,
                Top: 2225,
                Height: 21,
                Width: 74,
              },
              {
                WordText: 'you',
                Left: 371,
                Top: 2230,
                Height: 21,
                Width: 42,
              },
              {
                WordText: 'for',
                Left: 421,
                Top: 2225,
                Height: 21,
                Width: 32,
              },
              {
                WordText: 'your',
                Left: 460,
                Top: 2230,
                Height: 21,
                Width: 52,
              },
              {
                WordText: 'business',
                Left: 520,
                Top: 2225,
                Height: 21,
                Width: 104,
              },
              {
                WordText: 'Please',
                Left: 650,
                Top: 2225,
                Height: 21,
                Width: 79,
              },
              {
                WordText: 'make',
                Left: 738,
                Top: 2225,
                Height: 21,
                Width: 63,
              },
              {
                WordText: 'all',
                Left: 810,
                Top: 2225,
                Height: 21,
                Width: 24,
              },
              {
                WordText: 'cheques',
                Left: 843,
                Top: 2225,
                Height: 26,
                Width: 100,
              },
              {
                WordText: 'payable',
                Left: 952,
                Top: 2225,
                Height: 26,
                Width: 92,
              },
              {
                WordText: 'to',
                Left: 1051,
                Top: 2226,
                Height: 20,
                Width: 22,
              },
              {
                WordText: "'Company",
                Left: 1082,
                Top: 2225,
                Height: 26,
                Width: 119,
              },
              {
                WordText: "Name'.",
                Left: 1210,
                Top: 2225,
                Height: 21,
                Width: 81,
              },
              {
                WordText: 'For',
                Left: 1302,
                Top: 2225,
                Height: 21,
                Width: 38,
              },
              {
                WordText: 'bank',
                Left: 1349,
                Top: 2225,
                Height: 21,
                Width: 56,
              },
              {
                WordText: 'transfers',
                Left: 1412,
                Top: 2225,
                Height: 21,
                Width: 104,
              },
              {
                WordText: "'HSBC',",
                Left: 1525,
                Top: 2224,
                Height: 25,
                Width: 90,
              },
              {
                WordText: 'sort',
                Left: 1625,
                Top: 2226,
                Height: 20,
                Width: 43,
              },
              {
                WordText: 'code',
                Left: 1676,
                Top: 2225,
                Height: 21,
                Width: 57,
              },
            ],
            MaxHeight: 26,
            MinTop: 2224,
          },
          {
            LineText: '00-00-00, Account no. 01010101.',
            Words: [
              {
                WordText: '00-00-00,',
                Left: 815,
                Top: 2259,
                Height: 23,
                Width: 111,
              },
              {
                WordText: 'Account',
                Left: 936,
                Top: 2258,
                Height: 21,
                Width: 96,
              },
              {
                WordText: 'no.',
                Left: 1040,
                Top: 2263,
                Height: 16,
                Width: 34,
              },
              {
                WordText: '01010101.',
                Left: 1084,
                Top: 2259,
                Height: 20,
                Width: 123,
              },
            ],
            MaxHeight: 23,
            MinTop: 2258,
          },
          {
            LineText:
              'MJ Electrical Services, Registered in England & Wales, VAT number 9584 158 35',
            Words: [
              {
                WordText: 'MJ',
                Left: 541,
                Top: 2358,
                Height: 21,
                Width: 33,
              },
              {
                WordText: 'Electrical',
                Left: 585,
                Top: 2358,
                Height: 21,
                Width: 104,
              },
              {
                WordText: 'Services,',
                Left: 699,
                Top: 2358,
                Height: 24,
                Width: 106,
              },
              {
                WordText: 'Registered',
                Left: 817,
                Top: 2358,
                Height: 26,
                Width: 125,
              },
              {
                WordText: 'in',
                Left: 952,
                Top: 2358,
                Height: 21,
                Width: 19,
              },
              {
                WordText: 'England',
                Left: 981,
                Top: 2358,
                Height: 26,
                Width: 95,
              },
              {
                WordText: '&',
                Left: 1085,
                Top: 2358,
                Height: 21,
                Width: 16,
              },
              {
                WordText: 'Wales,',
                Left: 1110,
                Top: 2358,
                Height: 24,
                Width: 79,
              },
              {
                WordText: 'VAT',
                Left: 1198,
                Top: 2358,
                Height: 21,
                Width: 52,
              },
              {
                WordText: 'number',
                Left: 1258,
                Top: 2358,
                Height: 21,
                Width: 90,
              },
              {
                WordText: '9584',
                Left: 1355,
                Top: 2359,
                Height: 20,
                Width: 59,
              },
              {
                WordText: '158',
                Left: 1424,
                Top: 2359,
                Height: 20,
                Width: 41,
              },
              {
                WordText: '35',
                Left: 1474,
                Top: 2359,
                Height: 20,
                Width: 28,
              },
            ],
            MaxHeight: 26,
            MinTop: 2358,
          },
          {
            LineText: 'CORGI',
            Words: [
              {
                WordText: 'CORGI',
                Left: 1028,
                Top: 2533,
                Height: 15,
                Width: 58,
              },
            ],
            MaxHeight: 15,
            MinTop: 2533,
          },
        ],
        HasOverlay: true,
        Message: 'Total lines: 48',
      },
      TextOrientation: '0',
      FileParseExitCode: 1,
      ParsedText:
        "Invoice INVOOIO\r\nTo\r\nJackie Kensington\r\n18 High St\r\nWickham\r\nWK12 6HK\r\nCertificate Number CER/123-34\r\nEngineer David\r\nItem\r\nElectrical Labour\r\nElectrical\r\nSevices Lü•nited\r\nFrom\r\nMJ Electrical Services\r\n17 Harold Grove, Woodhouse, Leeds,\r\nWest Yorkshire, LS6 2EZ\r\nEmail: info@ mj-electrcial.co.uk\r\nDue Date\r\nInvoice Date\r\nTel: 441132816781\r\n17th Mar 2012\r\n16th Feb 2012\r\nQuantity Unit Price Line Price\r\nInstallation carried out on flat 18. Installed 3 new\r\nbrass effect plug fittings. Checked fuses.\r\nReconnected light switch and fitted dimmer in living\r\nroom. 4 hours on site at f 33 per hour.\r\nVolex 13A 2G DP sw Skt Wht Ins BB Round Edge Brass Effect\r\nVolex 4G IW 250W Dimmer Brushed Brass Round Edge\r\n4\r\n3\r\n1\r\nSubtotal\r\nVAT\r\nTotal\r\n233.00\r\n215.57\r\n232.00\r\n2132.00\r\n246.71\r\nE32.OO\r\n2210.71\r\n242.14\r\n2252.85\r\nThank you for your business Please make all cheques payable to 'Company Name'. For bank transfers 'HSBC', sort code\r\n00-00-00, Account no. 01010101.\r\nMJ Electrical Services, Registered in England & Wales, VAT number 9584 158 35\r\nCORGI\r\n",
      ErrorMessage: '',
      ErrorDetails: '',
    },
  ],
  OCRExitCode: 1,
  IsErroredOnProcessing: false,
  ProcessingTimeInMilliseconds: '1578',
  SearchablePDFURL: 'Searchable PDF not generated as it was not requested.',
};
